name: milkdromeda_icons
description: Open-source icons for general use made by Milkdromeda. Provides 100 icons in 2 sets.
version: 0.0.1+3
homepage: https://milkdromeda.dev
repository: https://github.com/milkdromeda-dev/milkdromeda_icons.git
issue_tracker: https://github.com/milkdromeda-dev/milkdromeda_icons/issues

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: MilkdromedaIconsSet1
      fonts:
        - asset: lib/fonts/MilkdromedaIconsSet1.ttf
    - family: MilkdromedaIconsSet2
      fonts:
        - asset: lib/fonts/MilkdromedaIconsSet2.ttf